adds readme with wireframes
INF6420/ss22-JMarcussen pull request #2
Opened 2023-05-19 03:16 UTC by JMarcussen

2023-05-19 03:48 UTC, JMarcussen commented
Hi @axamei , I believe I have completed the assignment, however the images are not showing when I preview. Is there a way I can fix this? Thanks!

2023-05-19 16:30 UTC, axamei commented
@JMarcussen The format of the image reference needs to change. Change to include the folder, the curly braces should be replaced by the square brackets, and no space between the square bracket and parentheses, e.g., `![Wireframe of Home Page](wireframes/Wireframes-examples-01.jpg)`

2023-05-19 16:31 UTC, axamei requested changes

2023-05-19 16:31 UTC, axamei commented on README.md
> +!{Wireframe of Home Page} (Wireframes-example-01.jpg)
Change to `![Wireframe of Home Page](wireframes/Wireframes-examples-01.jpg)`

2023-05-19 16:31 UTC, axamei commented on README.md
> +!{Wireframe of Work Page} (Wireframes-example-02.jpg)
Change to correct format and include folder

2023-05-19 16:31 UTC, axamei commented on README.md
> +!{Wireframe of About Page} (Wireframes-example-03.jpg)
Change to correct format and include folder

2023-05-22 17:35 UTC, axamei commented
@JMarcussen Please make sure these changes are made before Thursday.

2023-05-28 21:32 UTC, axamei commented
@JMarcussen I still don't see the requested changes in this branch. Please reach out to me.

2023-05-28 21:57 UTC, JMarcussen commented
@axamei do I create a new pull request now that the changes have been made?

2023-05-28 21:59 UTC, axamei commented
@JMarcussen make a commit with the requested changes and then push the branch. It should show up here.

2023-05-28 22:42 UTC, JMarcussen commented
All set. Made a commit, and then pushed the branch.

2023-06-02 03:32 UTC, closed without merging